name: Deploy
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # fetch whole history (needed for blog article creation time to work correctly)
          fetch-depth: 0
      - uses: pnpm/action-setup@v4.2.0
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'
      - run: pnpm i
      - name: Build 🔧
        run: pnpm build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: public
      - name: on deployment success
        if: env.deployment_status == 'success'
        run: echo "Deployment success"

