name: Deploy
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: skipcheck
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: echo skipping github pages deploy (dependabot)
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: |
          yarn
          yarn build
      - name: Deploy 🚀
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: public
