name: Sync articles with 3rd party
on: workflow_dispatch
jobs:
  sync-articles-with-3rd-party:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'
      - run: pnpm i
      - name: sync articles
        env:
          MEDIUM_TOKEN_FRS: ${{ secrets.MEDIUM_TOKEN_FRS }}
        run: cd packages/blog && pnpm sync-posts --sync-with-medium
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: add updated articles after sync [no ci]"
          file_pattern: 'packages/blog/.vitepress/*'
          disable_globbing: true

