name: Test build
on: [push]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
      - run: pnpm i
      - name: Build 🔧
        run: pnpm build
