name: Test build
on: [push]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.2.0
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'
      - run: pnpm i
      - name: Build 🔧
        run: pnpm build
